#WORKDIR /app
FROM adoptopenjdk/openjdk13:latest

COPY payment-service/target/payment-service-1.0-SNAPSHOT.jar /

CMD ["java","-Djava.security.egd=file:/dev/./urandom","-Dspring.profiles.active=production,gcp","-jar","/payment-service-1.0-SNAPSHOT.jar"]
