apiVersion: v1
kind: Service
metadata:
  name: payment-lb
  namespace: service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: payment-lb
spec:
  type: LoadBalancer
  selector:
    app: payment
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
